
modLoader="javafml" #mandatory
loaderVersion="[42,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3"

[[mods]] #mandatory
modId="scriptedmodels" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Scripted Models" #mandatory
logoFile="icon.png" #optional
authors="PixelDots" #optional
description='''
a Character Editor using Scripts
'''

[[dependencies.scriptedmodels]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[42,)" #mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.scriptedmodels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
